# Root directory of your project
root = "."
tmp_dir = "tmp"

[build]
  # Command to build your app (output binary inside tmp folder)
  cmd = "go build -o ./tmp/main ./cmd/app"
  bin = "tmp/main"
  full_bin = "./tmp/main"

  # Watch these extensions for changes
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Ignore vendor and tmp
  exclude_dir = ["vendor", "tmp"]

[log]
  time = true
  color = true