# Root directory of your project
root = "."
tmp_dir = "tmp"

[build]
  # Compile your app to tmp/main
  cmd = "go build -o ./tmp/main ./cmd/app"
  bin = "./tmp/main"

  # Watch only relevant file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Ignore noise dirs
  exclude_dir = ["vendor", "tmp", ".git"]

[log]
  color = true
  timestamp = true
